from django.urls import path

from tracker import views

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("account/", views.AccountView.as_view(), name="account"),
    path("opportunities/", views.OpportunityListView.as_view(), name="opportunity_list"),
    path("opportunities/board/", views.OpportunityBoardView.as_view(), name="opportunity_board"),
    path("opportunities/new/", views.OpportunityCreateView.as_view(), name="opportunity_create"),
    path("opportunities/<int:pk>/", views.OpportunityDetailView.as_view(), name="opportunity_detail"),
    path("opportunities/<int:pk>/edit/", views.OpportunityUpdateView.as_view(), name="opportunity_edit"),
    path("opportunities/<int:pk>/status/", views.StatusChangeView.as_view(), name="opportunity_status"),
    path("opportunities/<int:pk>/archive/", views.OpportunityArchiveView.as_view(), name="opportunity_archive"),
    path("opportunities/<int:pk>/duplicate/", views.OpportunityDuplicateView.as_view(), name="opportunity_duplicate"),
    path("opportunities/<int:pk>/delete/", views.OpportunityDeleteView.as_view(), name="opportunity_delete"),
    path("opportunities/<int:pk>/checklist/<int:item_id>/", views.ChecklistToggleView.as_view(), name="checklist_toggle"),
    path("opportunities/<int:pk>/checklist/", views.ChecklistAddView.as_view(), name="checklist_add"),
    path("opportunities/<int:pk>/materials/", views.MaterialsSelectView.as_view(), name="opportunity_materials"),
    path("opportunities/<int:pk>/interviews/", views.InterviewCreateView.as_view(), name="interview_create"),
    path("opportunities/<int:pk>/interviews/<int:stage_id>/notes/", views.InterviewNoteCreateView.as_view(), name="interview_note"),
    path("opportunities/<int:pk>/brief.md", views.BriefExportView.as_view(), name="opportunity_brief"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/tracks/", views.TrackCreateView.as_view(), name="track_create"),
    path("profile/tracks/<int:pk>/", views.TrackUpdateView.as_view(), name="track_edit"),
    path("profile/tracks/<int:pk>/delete/", views.TrackDeleteView.as_view(), name="track_delete"),
    path("profile/experience/", views.ExperienceCreateView.as_view(), name="experience_create"),
    path("profile/experience/<int:pk>/delete/", views.ExperienceDeleteView.as_view(), name="experience_delete"),
    path("profile/projects/", views.ProjectCreateView.as_view(), name="project_create"),
    path("profile/projects/<int:pk>/delete/", views.ProjectDeleteView.as_view(), name="project_delete"),
    path("materials/", views.MaterialListView.as_view(), name="materials"),
    path("materials/<int:pk>/delete/", views.MaterialDeleteView.as_view(), name="material_delete"),
    path("materials/<int:pk>/download/", views.MaterialDownloadView.as_view(), name="material_download"),
    path("tasks/", views.TaskListView.as_view(), name="tasks"),
    path("tasks/<int:pk>/toggle/", views.TaskToggleView.as_view(), name="task_toggle"),
    path("tasks/<int:pk>/delete/", views.TaskDeleteView.as_view(), name="task_delete"),
    path("contacts/", views.ContactListView.as_view(), name="contacts"),
    path("contacts/<int:pk>/", views.ContactDetailView.as_view(), name="contact_detail"),
    path("contacts/<int:pk>/delete/", views.ContactDeleteView.as_view(), name="contact_delete"),
    path("templates/", views.TemplateCreateView.as_view(), name="template_create"),
    path("templates/<int:pk>/delete/", views.TemplateDeleteView.as_view(), name="template_delete"),
    path("analytics/", views.AnalyticsView.as_view(), name="analytics"),
    path("import-export/", views.ImportExportView.as_view(), name="import_export"),
    path("export/<str:kind>/", views.ExportDownloadView.as_view(), name="export_download"),
]
