# Generated by Django 6.1.1 on 2026-09-13 05:50

import django.db.models.deletion
import django.utils.timezone
import tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_number', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_name', models.CharField(max_length=120)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=80)),
                ('interviewer_names', models.CharField(blank=True, max_length=300)),
                ('interviewer_roles', models.CharField(blank=True, max_length=300)),
                ('next_step', models.CharField(blank=True, max_length=300)),
                ('expected_response_date', models.DateField(blank=True, null=True)),
                ('thank_you_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['scheduled_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover letter'), ('portfolio', 'Portfolio / project link'), ('transcript', 'Transcript / supporting document'), ('pitch', 'Short pitch'), ('recruiter_questions', 'Recruiter questions'), ('interview_story', 'Interview story / notes')], max_length=32)),
                ('file', models.FileField(blank=True, upload_to=tracker.models.material_upload_to)),
                ('link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationMaterialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('material_type', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_snapshots', to='tracker.application')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='tracker.applicationmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('role_title', models.CharField(blank=True, max_length=200)),
                ('relationship', models.CharField(choices=[('recruiter', 'Recruiter'), ('employee', 'Employee'), ('alumni', 'Alumni'), ('professor', 'Professor'), ('career_fair', 'Career-fair contact'), ('referral', 'Referral'), ('other', 'Other')], default='other', max_length=32)),
                ('profile_link', models.URLField(blank=True)),
                ('channel', models.CharField(blank=True, max_length=80)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('referral_status', models.CharField(choices=[('none', 'No referral'), ('requested', 'Requested'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed')], default='none', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('channel', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='tracker.contact')),
            ],
            options={
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InterviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('topics', 'Topics to prepare'), ('technical', 'Technical questions'), ('behavioral', 'Behavioral questions'), ('ask_employer', 'Questions to ask the employer'), ('star', 'STAR examples'), ('general', 'Interview notes')], default='general', max_length=20)),
                ('content', models.TextField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tracker.interviewstage')),
            ],
            options={
                'ordering': ['note_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('company_site', 'Company site'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('referral', 'Referral'), ('career_fair', 'Career fair'), ('recruiter', 'Recruiter'), ('professor', 'Professor'), ('alumni', 'Alumni'), ('other', 'Other')], default='other', max_length=32)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('work_arrangement', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('role_type', models.CharField(choices=[('internship', 'Internship'), ('coop', 'Co-op'), ('new_grad', 'New grad'), ('contract', 'Contract'), ('part_time', 'Part-time'), ('full_time', 'Full-time')], default='internship', max_length=20)),
                ('posting_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('degree_requirements', models.TextField(blank=True)),
                ('experience_requirements', models.TextField(blank=True)),
                ('sponsorship_status', models.CharField(choices=[('unknown', 'Unknown'), ('appears_available', 'Appears available'), ('not_available', 'Not available'), ('user_verified', 'User verified')], default='unknown', max_length=32)),
                ('salary', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('researching', 'Researching'), ('preparing', 'Preparing'), ('applied', 'Applied'), ('recruiter_contacted', 'Recruiter Contacted'), ('recruiter_screen', 'Recruiter Screen'), ('online_assessment', 'Online Assessment'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed/Expired')], default='saved', max_length=32)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('priority_override_reason', models.CharField(blank=True, max_length=300)),
                ('is_archived', models.BooleanField(default=False)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('match_category', models.CharField(choices=[('strong', 'Strong'), ('possible', 'Possible'), ('weak', 'Weak'), ('unknown', 'Not yet scored')], default='unknown', max_length=16)),
                ('match_payload', models.JSONField(blank=True, default=dict)),
                ('last_status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='interviewstage',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_stages', to='tracker.opportunity'),
        ),
        migrations.AddField(
            model_name='contact',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='tracker.opportunity'),
        ),
        migrations.AddField(
            model_name='application',
            name='opportunity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='tracker.opportunity'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('degree', models.CharField(blank=True, max_length=120)),
                ('major', models.CharField(blank=True, max_length=120)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('preferred_role_categories', models.CharField(blank=True, help_text='Comma-separated role categories, e.g. Software, Embedded/Systems', max_length=400)),
                ('preferred_locations', models.CharField(blank=True, max_length=400)),
                ('work_arrangement_preference', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('work_authorization', models.CharField(choices=[('us_citizen', 'U.S. citizen'), ('permanent_resident', 'Permanent resident'), ('visa_holder', 'Current visa holder'), ('needs_sponsorship', 'Will need sponsorship'), ('other', 'Other / unspecified')], default='other', max_length=32)),
                ('sponsorship_preference', models.CharField(choices=[('required', 'I need sponsorship'), ('preferred', 'Sponsorship would help'), ('not_needed', 'I do not need sponsorship')], default='not_needed', max_length=20)),
                ('professional_pitch', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('experience_type', models.CharField(default='work', help_text='work, coursework, certification, or achievement', max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='tracker.profile')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProfileTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('keywords', models.TextField(blank=True, help_text='Comma or newline separated keywords')),
                ('pitch', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tracker.profile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='selected_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='tracker.profiletrack'),
        ),
        migrations.AddField(
            model_name='applicationmaterial',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='tracker.profiletrack'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('technologies', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True)),
                ('highlights', models.TextField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tracker.profile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SavedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('template_type', models.CharField(default='message', max_length=40)),
                ('body', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(db_index=True, max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proficiency', models.CharField(blank=True, max_length=80)),
                ('evidence_notes', models.TextField(blank=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_skills', to='tracker.profiletrack')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_links', to='tracker.skill')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(choices=[('saved', 'Saved'), ('researching', 'Researching'), ('preparing', 'Preparing'), ('applied', 'Applied'), ('recruiter_contacted', 'Recruiter Contacted'), ('recruiter_screen', 'Recruiter Screen'), ('online_assessment', 'Online Assessment'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed/Expired')], max_length=32)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tracker.opportunity')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('task_type', models.CharField(choices=[('apply', 'Apply'), ('tailor', 'Tailor materials'), ('research', 'Research'), ('message', 'Message'), ('follow_up', 'Follow up'), ('interview_prep', 'Interview preparation'), ('thank_you', 'Thank-you note'), ('other', 'Other')], default='other', max_length=32)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tracker.contact')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completed', 'due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tracker.opportunity')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'key'), name='unique_checklist_key')],
            },
        ),
        migrations.CreateModel(
            name='OpportunitySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('required', 'Required'), ('preferred', 'Preferred')], max_length=16)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='tracker.opportunity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'normalized_name', 'kind'), name='unique_opp_skill_kind')],
            },
        ),
        migrations.AddConstraint(
            model_name='profiletrack',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='unique_track_name_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('user', 'normalized_name'), name='unique_skill_per_user'),
        ),
        migrations.AddConstraint(
            model_name='profileskill',
            constraint=models.UniqueConstraint(fields=('track', 'skill'), name='unique_skill_per_track'),
        ),
    ]
