# Generated by Django 6.1.1 on 2026-09-14 03:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplifyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing_key', models.CharField(max_length=64, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=400)),
                ('apply_url', models.URLField(blank=True, max_length=1000)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('age_label', models.CharField(blank=True, max_length=16)),
                ('age_days', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['age_days', '-first_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='simplify_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='openings_last_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='source',
            field=models.CharField(choices=[('company_site', 'Company site'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('referral', 'Referral'), ('career_fair', 'Career fair'), ('recruiter', 'Recruiter'), ('professor', 'Professor'), ('alumni', 'Alumni'), ('simplify', 'SimplifyJobs list'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='UserListingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='tracker.simplifylisting')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_states', to='tracker.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'listing'), name='unique_user_listing')],
            },
        ),
    ]
