# Generated by Django 6.1.1 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_gmailaccount_gmailprocessedmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmailaccount",
            name="spreadsheet_id",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
