# Generated by Django 6.1.1 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_gmailaccount_spreadsheet_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmailprocessedmessage",
            name="parser_version",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
