# Generated by Django 6.1.1 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_gmailprocessedmessage_parser_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="gmailprocessedmessage",
            name="application_key",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="gmailprocessedmessage",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gmailprocessedmessage",
            name="parse_status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="gmailprocessedmessage",
            name="subject",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="gmailprocessedmessage",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gmailprocessedmessage",
            name="tab",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="gmailprocessedmessage",
            name="thread_id",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
